name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    label: 'type: enhancement'
  - title: 'Bug Fixes'
    label: 'type: bug'
  - title: 'Documentation'
    label: 'type: docs'
  - title: 'Dependency Updates'
    label: 'type: dependencies'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escape: '\<*_&'
version-resolver:
  major:
    labels:
      - 'version: major'
  minor:
    labels:
      - 'version: minor'
  patch:
    lables:
      - 'version: patch'
  default: patch
template: |
  ## Changes

  $CHANGES
